### ISSUE TITLE
Controlling color styling with CSS 

### ISSUE THREAD

**Issue by tupaje1** [flexicious/webcomponents-datagrid-polymer-starter-kit#4]
Currently, we are not able to control the color styling with CSS because of the inline style tag having top precedence. Using the settings-parser.js to control the color styling is not suitable because it relies on  setting inline style attributes to a HTML elements created on the fly which makes it difficult to apply our color theming. Can you please extract the color styling to an external style sheet?

**Comment by flexicious** [comment]
Fixed with latest commit
